services:
  postgres:
    image: postgres:16
    network_mode: host
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    #ports:
    #  - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 10
  trigger_pipeline:
    restart: never
    profiles:
      - do_not_start
    build: ./services/
    network_mode: host
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ARUANNE_DIR: /data/aruanne
      TARGET_FILENAME: 'LN002 Laenude võlgnevus.xlsx'
    volumes:
      - ./aruanne:/data/aruanne:ro
      - ./services/utils.py:/app/utils.py:ro
      - ./services/ingest.py:/app/ingest.py:ro
      - ./services/transform.py:/app/transform.py:ro
      - ./services/run_pipeline.py:/app/run_pipeline.py:ro
      - ./logs:/app/logs/
    working_dir: /app 
    command: python run_pipeline.py
    depends_on:
      postgres:
        condition: service_healthy
  pipeline:
    build: ./services/
    network_mode: host
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ARUANNE_DIR: /data/aruanne
      TARGET_FILENAME: 'LN002 Laenude võlgnevus.xlsx'
    volumes:
      - ./aruanne:/data/aruanne:ro
      - ./services/utils.py:/app/utils.py:ro
      - ./services/ingest.py:/app/ingest.py:ro
      - ./services/transform.py:/app/transform.py:ro
      - ./services/run_pipeline.py:/app/run_pipeline.py:ro
      - ./services/scheduler.py:/app/scheduler.py:ro
      - ./logs:/app/logs/
    working_dir: /app 
    command: python scheduler.py
    depends_on:
      postgres:
        condition: service_healthy
  api:
    network_mode: host
    build: ./services/
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./services/utils.py:/app/utils.py:ro
      - ./services/api.py:/app/api.py:ro
      - ./services/templates:/app/templates:ro
      - ./services/static:/app/static:ro
      - ./logs:/app/logs/
    working_dir: /app 
    command: flask --app api run --host '0.0.0.0' --port 5000 --debug
    depends_on:
      postgres:
        condition: service_healthy
    #ports:
    #  - "5000:5000"
volumes:
  pgdata:
